#!/usr/bin/env bash
# =============================================================================
#  bootstrap.sh — claude-workflow installer
#  Usage: curl -fsSL https://raw.githubusercontent.com/JeffreyGbeho/claude-workflow/main/bootstrap.sh | bash
# =============================================================================

set -e

REPO="JeffreyGbeho/claude-workflow"
INSTALL_DIR="$HOME/.claude-workflow"
BIN_NAME="cwf"
RAW_BASE="https://raw.githubusercontent.com/${REPO}/main"

BOLD="\033[1m"
RESET="\033[0m"
GREEN="\033[32m"
BLUE="\033[34m"
RED="\033[31m"
CYAN="\033[36m"
DIM="\033[2m"

print_banner() {
  echo ""
  echo -e "${BLUE}${BOLD}"
  echo "  ╔══════════════════════════════════════════════════╗"
  echo "  ║        claude-workflow Installation              ║"
  echo "  ║   Configure Claude Code on GitHub & GitLab       ║"
  echo "  ╚══════════════════════════════════════════════════╝"
  echo -e "${RESET}"
  echo ""
}

print_ok()   { echo -e "${GREEN}  ✓ $1${RESET}"; }
print_err()  { echo -e "${RED}  ✗ $1${RESET}"; }
print_info() { echo -e "${DIM}  $1${RESET}"; }
print_step() { echo -e "${CYAN}${BOLD}▶ $1${RESET}"; }

# ── Detect OS ────────────────────────────────────────────────────────────────
detect_shell_profile() {
  if [ -n "$ZSH_VERSION" ] || [ "$SHELL" = "$(which zsh 2>/dev/null)" ]; then
    echo "$HOME/.zshrc"
  elif [ -n "$BASH_VERSION" ] || [ "$SHELL" = "$(which bash 2>/dev/null)" ]; then
    if [ -f "$HOME/.bash_profile" ]; then
      echo "$HOME/.bash_profile"
    else
      echo "$HOME/.bashrc"
    fi
  else
    echo "$HOME/.profile"
  fi
}

detect_bin_dir() {
  # Look for a directory in PATH writable without sudo
  for dir in "$HOME/.local/bin" "$HOME/bin" "/usr/local/bin"; do
    if [ -d "$dir" ] && [ -w "$dir" ]; then
      echo "$dir"
      return
    fi
  done
  # Create ~/.local/bin if nothing is available
  mkdir -p "$HOME/.local/bin"
  echo "$HOME/.local/bin"
}

# ── Check dependencies ───────────────────────────────────────────────────────
check_deps() {
  print_step "Checking dependencies..."
  local missing=0

  for cmd in git curl bash; do
    if command -v "$cmd" &>/dev/null; then
      print_ok "$cmd"
    else
      print_err "$cmd is missing"
      missing=1
    fi
  done

  if [ "$missing" -eq 1 ]; then
    echo ""
    print_err "Install the missing dependencies and re-run the installation."
    exit 1
  fi
}

# ── Download files ────────────────────────────────────────────────────────────
download_files() {
  print_step "Downloading claude-workflow..."

  # Create install directory
  mkdir -p "$INSTALL_DIR"

  # Download main script
  curl -fsSL "${RAW_BASE}/src/install-claude-workflow.sh" -o "$INSTALL_DIR/install-claude-workflow.sh"
  chmod +x "$INSTALL_DIR/install-claude-workflow.sh"
  print_ok "Main script downloaded"

  # Download update script
  curl -fsSL "${RAW_BASE}/src/update.sh" -o "$INSTALL_DIR/update.sh"
  chmod +x "$INSTALL_DIR/update.sh"
  print_ok "Update script downloaded"

  # Save installed version
  curl -fsSL "${RAW_BASE}/VERSION" -o "$INSTALL_DIR/VERSION" 2>/dev/null || echo "1.0.0" > "$INSTALL_DIR/VERSION"
  local version
  version=$(cat "$INSTALL_DIR/VERSION")
  print_ok "Version $version installed"
}

# ── Create global command ─────────────────────────────────────────────────────
create_command() {
  print_step "Creating global command..."

  local bin_dir
  bin_dir=$(detect_bin_dir)

  # Create wrapper that routes commands
  cat > "$bin_dir/$BIN_NAME" << 'WRAPPER'
#!/usr/bin/env bash
# Wrapper cwf — auto-generated by bootstrap.sh
INSTALL_DIR="$HOME/.claude-workflow"

# Check for updates in background (silent)
if [ -f "$INSTALL_DIR/update.sh" ]; then
  bash "$INSTALL_DIR/update.sh" --silent &
fi

show_help() {
  echo "Usage: cwf <command>"
  echo ""
  echo "Commands:"
  echo "  init                    Configure claude-workflow in current project"
  echo "  status                  Show issues, branches, and MR status"
  echo "  issues                  Analyze all issues and propose a plan"
  echo "  issues start            Start working after plan validation"
  echo "  issue <n>               Work on a specific issue"
  echo "  issue <n> --interactive Work on issue with terminal questions"
  echo ""
  echo "Options:"
  echo "  --update                Force update cwf"
  echo "  --uninstall             Uninstall cwf"
}

case "$1" in
  init)
    exec bash "$INSTALL_DIR/install-claude-workflow.sh"
    ;;
  status)
    exec claude "/cwf-status"
    ;;
  issues)
    shift
    exec claude "/cwf-issues $*"
    ;;
  issue)
    shift
    exec claude "/cwf-issue $*"
    ;;
  --update)
    exec bash "$INSTALL_DIR/update.sh" --force
    ;;
  --uninstall)
    exec bash "$INSTALL_DIR/update.sh" --uninstall
    ;;
  ""|--help|-h)
    show_help
    ;;
  *)
    echo "Unknown command: $1"
    echo ""
    show_help
    exit 1
    ;;
esac
WRAPPER
  chmod +x "$bin_dir/$BIN_NAME"
  print_ok "Command created at $bin_dir/$BIN_NAME"

  # Add to PATH if needed
  local profile
  profile=$(detect_shell_profile)

  if ! echo "$PATH" | grep -q "$bin_dir"; then
    echo "" >> "$profile"
    echo "# claude-workflow" >> "$profile"
    echo "export PATH=\"$bin_dir:\$PATH\"" >> "$profile"
    print_ok "PATH updated in $profile"
    NEED_RELOAD=true
  fi
}

# ── Final message ─────────────────────────────────────────────────────────────
print_success() {
  echo ""
  echo -e "${GREEN}${BOLD}  ✓ Installation complete!${RESET}"
  echo ""
  echo -e "${CYAN}${BOLD}  To get started:${RESET}"

  if [ "$NEED_RELOAD" = "true" ]; then
    local profile
    profile=$(detect_shell_profile)
    echo ""
    echo -e "  1. Reload your terminal:"
    echo -e "     ${BOLD}source ${profile}${RESET}"
    echo ""
    echo -e "  2. Go to a project and configure:"
    echo -e "     ${BOLD}cwf init${RESET}"
  else
    echo ""
    echo -e "  Go to a project and configure:"
    echo -e "     ${BOLD}cwf init${RESET}"
  fi

  echo ""
  echo -e "${CYAN}${BOLD}  Then use:${RESET}"
  echo -e "  ${BOLD}cwf status${RESET}              → see issues and MR status"
  echo -e "  ${BOLD}cwf issues${RESET}              → plan all issues"
  echo -e "  ${BOLD}cwf issue 42${RESET}            → work on issue #42"
  echo ""
  echo -e "${DIM}  cwf --update    Force update${RESET}"
  echo -e "${DIM}  cwf --uninstall Uninstall${RESET}"
  echo ""
}

# ── Entry point ───────────────────────────────────────────────────────────────
main() {
  print_banner
  check_deps
  download_files
  create_command
  print_success
}

main "$@"
