#!/usr/bin/env bash
# =============================================================================
#  update.sh — Checks and applies claude-workflow updates
# =============================================================================

REPO="JeffreyGbeho/claude-workflow"
INSTALL_DIR="$HOME/.claude-workflow"
RAW_BASE="https://raw.githubusercontent.com/${REPO}/main"
UPDATE_FLAG="$INSTALL_DIR/.update-available"

print_ok()   { echo -e "\033[32m  ✓ $1\033[0m"; }
print_info() { echo -e "\033[2m  $1\033[0m"; }
print_step() { echo -e "\033[36m\033[1m▶ $1\033[0m"; }

# ── Silent check (background) — just write a flag if update available ────────
check_silent() {
  local remote_version
  remote_version=$(curl -fsSL --max-time 5 "${RAW_BASE}/VERSION" 2>/dev/null || echo "")
  [ -z "$remote_version" ] && return 0

  local local_version
  local_version=$(cat "$INSTALL_DIR/VERSION" 2>/dev/null || echo "0.0.0")

  if [ "$remote_version" != "$local_version" ]; then
    echo "$remote_version" > "$UPDATE_FLAG"
  else
    rm -f "$UPDATE_FLAG"
  fi
}

# ── Show update notice (called by wrapper) ───────────────────────────────────
show_notice() {
  if [ -f "$UPDATE_FLAG" ]; then
    local new_version
    new_version=$(cat "$UPDATE_FLAG")
    local local_version
    local_version=$(cat "$INSTALL_DIR/VERSION" 2>/dev/null || echo "0.0.0")
    echo -e "\033[33m  ⚡ Update available: v$local_version → v$new_version — run \033[1mcwf update\033[0;33m to update\033[0m"
    echo ""
  fi
}

# ── Update the cwf wrapper script ─────────────────────────────────────────────
update_wrapper() {
  # Find where cwf is installed
  local wrapper_path=""
  for dir in "$HOME/.local/bin" "$HOME/bin" "/usr/local/bin"; do
    if [ -f "$dir/cwf" ]; then
      wrapper_path="$dir/cwf"
      break
    fi
  done

  if [ -z "$wrapper_path" ]; then
    print_info "cwf wrapper not found, skipping wrapper update"
    return 0
  fi

  cat > "$wrapper_path" << 'WRAPPER'
#!/usr/bin/env bash
# Wrapper cwf — auto-generated by update.sh
INSTALL_DIR="$HOME/.claude-workflow"

# Check for updates in background (silent)
if [ -f "$INSTALL_DIR/update.sh" ]; then
  bash "$INSTALL_DIR/update.sh" --silent &
fi

# Show update notice if available
if [ -f "$INSTALL_DIR/update.sh" ]; then
  bash "$INSTALL_DIR/update.sh" --notice
fi

show_help() {
  echo "Usage: cwf <command>"
  echo ""
  echo "Commands:"
  echo "  init                    Configure claude-workflow in current project"
  echo "  status                  Show issues, branches, and MR status"
  echo "  issues                  Analyze all issues and propose a plan"
  echo "  issues start            Start working after plan validation"
  echo "  issue <n>               Work on a specific issue"
  echo "  issue <n> --interactive Work on issue with terminal questions"
  echo "  update                  Update cwf to latest version"
  echo "  uninstall               Uninstall cwf"
}

case "$1" in
  init)
    exec bash "$INSTALL_DIR/install-claude-workflow.sh"
    ;;
  status)
    exec claude "/cwf-status"
    ;;
  issues)
    shift
    exec claude "/cwf-issues $*"
    ;;
  issue)
    shift
    exec claude "/cwf-issue $*"
    ;;
  update)
    exec bash "$INSTALL_DIR/update.sh" --update
    ;;
  uninstall)
    exec bash "$INSTALL_DIR/update.sh" --uninstall
    ;;
  ""|--help|-h)
    show_help
    ;;
  *)
    echo "Unknown command: $1"
    echo ""
    show_help
    exit 1
    ;;
esac
WRAPPER
  chmod +x "$wrapper_path"
  print_ok "Wrapper updated at $wrapper_path"
}

# ── Apply update ─────────────────────────────────────────────────────────────
apply_update() {
  local remote_version
  remote_version=$(curl -fsSL --max-time 10 "${RAW_BASE}/VERSION" 2>/dev/null || echo "")

  if [ -z "$remote_version" ]; then
    echo -e "\033[31m  ✗ Could not reach update server\033[0m"
    return 1
  fi

  local local_version
  local_version=$(cat "$INSTALL_DIR/VERSION" 2>/dev/null || echo "0.0.0")

  if [ "$remote_version" = "$local_version" ]; then
    print_ok "Already up to date (v$local_version)"
    return 0
  fi

  print_step "Updating v${local_version} → v${remote_version}..."

  curl -fsSL "${RAW_BASE}/src/install-claude-workflow.sh" -o "$INSTALL_DIR/install-claude-workflow.sh" && \
    chmod +x "$INSTALL_DIR/install-claude-workflow.sh"

  curl -fsSL "${RAW_BASE}/src/update.sh" -o "$INSTALL_DIR/update.sh" && \
    chmod +x "$INSTALL_DIR/update.sh"

  # Update the cwf wrapper in-place
  update_wrapper

  echo "$remote_version" > "$INSTALL_DIR/VERSION"
  rm -f "$UPDATE_FLAG"

  print_ok "Updated to v${remote_version}"
}

# ── Uninstall ─────────────────────────────────────────────────────────────────
uninstall() {
  echo ""
  echo -e "\033[1m  Uninstalling claude-workflow...\033[0m"
  echo ""

  rm -rf "$INSTALL_DIR"
  print_ok "$INSTALL_DIR directory removed"

  for dir in "$HOME/.local/bin" "$HOME/bin" "/usr/local/bin"; do
    if [ -f "$dir/cwf" ]; then
      rm -f "$dir/cwf"
      print_ok "Command removed from $dir"
    fi
  done

  echo ""
  echo -e "\033[2m  Files created in your projects (CLAUDE.md, .claude/) were not removed.\033[0m"
  echo ""
  print_ok "Uninstall complete"
}

# ── Entry point ───────────────────────────────────────────────────────────────
case "$1" in
  --silent)  check_silent ;;
  --notice)  show_notice ;;
  --update)  apply_update ;;
  --uninstall) uninstall ;;
  *)         apply_update ;;
esac
